name: "Update Brasileirão Data"
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  update-data:
    name: "Update Brasileirão Data"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run simulation
        run: python brasileirao_2026.py
      - name: Commit and push changes
        run: |
          git config user.name "lfkopp"
          git config user.email "lfkopp@gmail.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes detected."
          else
            git commit -m "feat: Automated Brasileirão data update $(date +'%Y-%m-%d')"
            git push
          fi
